### PR TITLE
Functional testing

### PR DESCRIPTION
**Pull request by tgross**
This PR will carry https://github.com/autopilotpattern/nginx/pull/37 and move the example backend into a functional testing rig. 

cc @misterbisson @jasonpincin

### CODE REVIEW

**Comment by tgross** [comment]
I've got an initial test rig done here. I want to get this running on Jenkins next and extend the test to have backends fail before merging this issue.

```
----------------------------------------------------------------------
NginxStackTest.test_scaleup
----------------------------------------------------------------------
elapsed  | task
22.99161 | docker-compose -f triton/docker-compose.yml -p nginx stop
29.78775 | docker-compose -f triton/docker-compose.yml -p nginx rm -f
106.3892 | docker-compose -f triton/docker-compose.yml -p nginx up -d
8.114008 | docker-compose -f triton/docker-compose.yml -p nginx ps
9.007755 | docker-compose -f triton/docker-compose.yml -p nginx ps
1.740094 | docker inspect nginx_consul_1
80.57586 | docker-compose -f triton/docker-compose.yml -p nginx scale backend=2
.
----------------------------------------------------------------------
Ran 1 test in 352.328s

OK
```

**Comment by tgross** [comment]
I've extended the tests but they're not stable right now. I'm getting erratic failures which all look to be timeout vs provisioning time and CNS latency issues.

```
----------------------------------------------------------------------
NginxStackTest.test_scaleup_and_down
----------------------------------------------------------------------
elapsed  | task
29.00812 | docker-compose -f triton/docker-compose.yml -p nginx stop
34.15193 | docker-compose -f triton/docker-compose.yml -p nginx rm -f
131.2256 | docker-compose -f triton/docker-compose.yml -p nginx up -d
13.61234 | docker-compose -f triton/docker-compose.yml -p nginx ps
17.34639 | docker-compose -f triton/docker-compose.yml -p nginx ps
4.732752 | docker inspect nginx_consul_1
41.79441 | docker-compose -f triton/docker-compose.yml -p nginx scale backend=2
8.058235 | wait_for_service: backend
2.693277 | docker exec nginx_backend_2 ifconfig eth0 down
10.08746 | wait_for_service: backend
1.987724 | docker exec nginx_backend_2 ifconfig eth0 up
27.20067 | wait_for_service: backend
.
----------------------------------------------------------------------
Ran 1 test in 503.974s
```

**Comment by tgross** [comment]
Ok, I think this is ready:

```
----------------------------------------------------------------------
NginxStackTest.test_scaleup_and_down
----------------------------------------------------------------------
elapsed  | task
19.42238 | docker-compose -f triton/docker-compose.yml -p nginx stop
36.57432 | docker-compose -f triton/docker-compose.yml -p nginx rm -f
55.77278 | docker-compose -f triton/docker-compose.yml -p nginx up -d
9.338359 | docker-compose -f triton/docker-compose.yml -p nginx ps
8.356574 | docker-compose -f triton/docker-compose.yml -p nginx ps
8.356976 | wait_for_containers: {'backend': 1, 'nginx': 1, 'consul': 1}
1.665717 | docker inspect nginx_consul_1
48.00144 | wait_for_service: backend
19.12659 | wait_for_service: containerpilot
5.037040 | wait_for_service: nginx
0.012039 | wait_for_service: nginx-public
0.111934 | wait_for_cns: 
48.77281 | docker-compose -f triton/docker-compose.yml -p nginx scale backend=2
10.49117 | docker-compose -f triton/docker-compose.yml -p nginx ps
10.49165 | wait_for_containers: {'backend': 2, 'nginx': 1, 'consul': 1}
0.003922 | wait_for_service: backend
5.210268 | docker exec nginx_backend_2 ifconfig eth0 down
9.067071 | wait_for_service: backend
1.886657 | docker exec nginx_backend_2 ifconfig eth0 up
2.014246 | wait_for_service: backend
.
----------------------------------------------------------------------
Ran 1 test in 341.341s

OK
Finished: SUCCESS
```

**Comment by jasonpincin** [comment]
Looks great to me. First time taking a good look at https://github.com/autopilotpattern/testing. Good stuff! Those tests are nice and easy to understand. Also, having the example app tucked away in the examples folder is so much cleaner IMHO. Less confusing trying to understand the repo now.

**Pull request merged**
